import 'package:retrofit_graphql/src/model/gq_queries.dart';

abstract class ClientSerilaizer {
  
  String serializeClient();

   String classNameFromType(GQQueryType type) {
    switch (type) {
      case GQQueryType.query:
        return "Queries";
      case GQQueryType.mutation:
        return "Mutations";
      case GQQueryType.subscription:
        return "Subscriptions";
    }
  }
}

const fileHeadComment = """
// GENERATED CODE - DO NOT MODIFY BY HAND. ANY MODIFICATION WILL BE LOST ON NEXT GENERATION
// Generated by retrofit_graphql
// GitHub: https://github.com/Oualitsen/retrofit-Graphql-For-Dart/
// Pub.dev https://pub.dev/packages/retrofit_graphql
// ignore_for_file: camel_case_types, constant_identifier_names, unused_import, non_constant_identifier_names
""";